### ISSUE TITLE
DpiScalingFactor not working, (fixed)

### ISSUE THREAD

**Issue by thomasvt** [MarcStan/monogame-framework-wpfinterop#20]
Hi,

First of all: I like what you did with this lib, thanks for that!

I have a 4K and full HD monitor and my windows zoom factor is set to 150%. So, I often have a lot of issues with pixel crispiness when programming. So, as I had blurry rendering, I found DpiScalingFactor, but that is actually never used internally, so that's why it doesn't change anything :)

Anyway... I didn't entirely understand where you were going with that factor, so I just added another solution where you have a bool UseDevicePixelSize property that internally creates the DX backbuffer size using devicepixel sizes instead of WPF's DIP size. Next to that I changed WpfMouse so that the position returned to the WpfGame also follows the UseDevicePixelSize setting.

If you're still active on the project, I can make a PR if you like...

**Comment by MarcStan** [comment]
Hey,

good catch. I originally implemented the scaling feature on a separate branch and must have made a mistake when merging it over. [These changes are missing](https://github.com/esengine/MonoGame.Framework.WpfInterop/commit/039f97f6b89bc4aacc99ec737c6cbd25d99ed7e1#diff-450ae3884eecfeaa705f1669d78a51e1L258-R281) which is why the value is never used internally.

Luckily someone still had the branch in a fork or this would have been hard to track down. 😀

I personally haven't used this library in a while but if you open a PR I'll happily take a look and merge it.
