### ISSUE TITLE
Delayed rendering under heavy load

### ISSUE THREAD

**Issue by georg-eckert-zeiss** [MarcStan/monogame-framework-wpfinterop#23]
Hi there again : )

I noticed behaviour which I could not really understand. I am rendering a very large mesh with MonoGame (10.000.000.000 Triangles) - I know, very large and I do not expect it to render without any stutters. I do this in the draw method. In the update method I process input from `WPFMouse`.

The funny thing is, when I try to move my object around, it is moving according to my mouse movement, but in a very delayed manner. When I stop my mouse, the movement continues for a few seconds until the whole movement has finished.

The only reason for this I could think of is the following:

1. WPF `OnRendering` is called at 60 FPS
2. `WPFGame` calls `WPFGame::Update` and `WPFGame::Draw` at the same interval
3. Even when load is very high, those 60 draw calls are performed
4. GPU is not fast enough and cannot draw 60 images per second
5. draw calles line up
6. GPU outputs images delayed
7. Input was processed at correct speed but I can see the images much later.

Is this correct or could you think of another explanation?

I really could not figure it out :' ( 

Cheers,
Georg

Edit: As a workaround I draw only every fifth frame to keep it usable. But I guess thats not the best way ^^"

**Comment by MarcStan** [comment]
You are spot on.

There is some [rudimentary logic](https://github.com/MarcStan/monogame-framework-wpfinterop/blob/141128acecbcd56287c4a124ff8a4d5507141049/MonoGame.Framework.WpfInterop/D3D11Host.cs#L540) to prevent running at > 60 FPS (or whatever the current WPF target FPS is) in the host but the [actual render function](https://github.com/MarcStan/monogame-framework-wpfinterop/blob/141128acecbcd56287c4a124ff8a4d5507141049/MonoGame.Framework.WpfInterop/WpfGame.cs#L142) is **very** primitive. ;)

MonoGame has [**IsRunningSlowly**](https://github.com/MonoGame/MonoGame/blob/5ddc1518ebf4eacecc5e454382967363c209e6a5/MonoGame.Framework/Game.cs#L485) which is used internally to skip some drawcalls in case of high load. I suppose the same logic could (and should) be used here as well to reduce the draw call count.

Happy to accept a PR; otherwise I'll try and take a look at it on the weekend.

**Comment by georg-eckert-zeiss** [comment]
Thanks for your fast reply. I am actually pretty new to graphics programming. I guess it would be better if you could have a look into the matter.

**Comment by MarcStan** [comment]
I did some testing and I am no longer certain this can be properly fixed in this library.

Whenever the system load increases the WPF `CompositionTarget.Rendering` event starts throtteling itself automatically.

This isn't something that I can influence (the event gets throttled as soon as one event takes longer than the allotted time (16ms at 60 FPS).

I tried to drop draw calls automatically whenever the load increases slightly (by measuring draw call duration and dropping a few when they start taking longer than `TargetElapsedTime`). Unfortunately at that time WPF already begins throtteling the rendering event.

I even tried to drop a lot of draw calls (e.g. 9/10) but it looks like any one draw call that takes longer than allowed is  enough for WPF to throttle the rendering loop for some time.

In my testcase the composition event never recovers beyond 40 FPS as soon as any one draw call takes longer than 16ms. Only once the load is reduced fully for a few seconds will it recover to 60 FPS.

As crude as it seems, dropping frames on your end under load may actually be a decent fix (apart from reducing the load in the first place ;) ).

I will try some more testing to see if I can solve it in the library but I can't guarantee anything since the solution would need to work properly for a wide variety of cases.

**Comment by georg-eckert-zeiss** [comment]
Yeah. That's pretty much what I tried, too. Thanks for having a look : )

**Comment by MarcStan** [comment]
I moved my changes to branch [experimental/skip-frames-under-load](https://github.com/MarcStan/monogame-framework-wpfinterop/tree/experimental/skip-frames-under-load) since I wasn't able to make it work in a satisfying way (framework FPS drop persists under load).

I will leave this issue open as it doesn't look like it can be fixed in the library.

**Comment by georg-eckert-zeiss** [comment]
Thanks for your work. I will fork that one and have a look what to make of it : )
