### ISSUE TITLE
How do I access the size of the WPF graphics area in the Initialize method?

### ISSUE THREAD

**Issue by Thraka** [MarcStan/monogame-framework-wpfinterop#30]
You can normally query the preferredbackbuffer sizes in the MonoGame initialize method, but here it's always 0. How do I figure this out? I was thinking i could query the `(RenderTarget2D)GraphicsDevice.GetRenderTargets()[0].RenderTarget` but that object doesn't exist during initialize.

**Comment by LynxStar** [comment]
Understandable frustration, I ran into similar issues with just dealing with the PresentationParameters in general behavior differently. `PreferredBackBufferWidth` and `PreferredBackBufferHeight` return the WPFGame's ActualWidth and ActualHeight which are properties supplied by WPF.

![image](https://user-images.githubusercontent.com/1655924/144695622-e37d1772-917b-4cfd-8da2-e6126733e3af.png)

`_host` is the WPFGame instance you pass in when you create the WpfGraphicsDeviceService

![image](https://user-images.githubusercontent.com/1655924/144695631-31ff0f58-d4cc-438c-b9e8-663816143632.png)

The reason that ActualWidth and Height are returning 0 is we're inside of a WPF object before the layout engine has placed the control. So it starts off at 0/0. If you override draw/update (which you need to if you want your WpfGame to do anything) and drop a breakpoint you'll see that ActualWidth and ActualHeight are now their precise values (stored as a double). 

So that still leaves the problem of how the heck do you access this before the first frame is rendered? Personally I hook the resize event in WPF `OnRenderSizeChanged`. This will fire before the first update or draw call.

This provides some extra complexity versus normal MonoGame since you can't just do everything inside of Initialize the way you normally do.

Some other considerations because of differences. PresentationParameters on the GraphicsDevice don't update on the normal cadence that MonoGame normally does, which is because of how the backbuffer is managed, so if you need to work with the ViewPort during initialization or stuff like that it'll be the default 800x400 until the first render pass; similarly it only updates on render.

Finally WpfGame's D3D11Host is DPI aware so if you are a monitor that isn't 1:1 ratio for DPI you might be confused at which glance with some numbers. I happen to work at 1:75:1 so I ran into that problem :)

Feel free to email me directly from my profile if you want more help. This has been my hobby project for the last few months.

**Comment by MarcStan** [comment]
Yes, unfortunately the behaviour between this version and a native MonoGame instance isn't identical in many places.

@LynxStar already provided you the reason and some possible workarounds. Another option I used before was to have a initialize block inside update/draw that is only called once when the game starts up.

**Comment by Thraka** [comment]
This is how I did do it to work around it. I have a game engine which works with multiple backends, one being MonoGame. A user of mine was wondering how they could get it working in WPF to create an editor, so I was exploring. The game engine is designed to be initialized at the same time as monogame and reads those values. I had to rework some of that but I got it working.

Thanks for the answer @LynxStar
